### PR TITLE
New features & bugfixes

### PR DESCRIPTION
**Pull request by mayerwin**
I haved implemented the features I suggested previously:
- Added option to start with Windows: A shortcut in the start menu to the current executable is created (or deleted). Quite clean and efficient.
- Added possibility to target specific audio devices: USB devices plugging and unplugging will also be detected (only if target devices include one other than the default playback device) to ensure the targeted audio devices are always "stimulated". Targeted devices are saved in the settings, and will not be lost even if the device is unplugged (it'll be reused the next time it is plugged in).
- Fixed issue when waking from sleep. Power state changes will be detected and the sounds will be restarted (they would stop otherwise).
- Added ILMerge task (with a nuget package) to create a standalone executable including the referenced NAudio.dll.

SPDIF-KA now uses NAudio instead of SoundPlayer. If Silence is selected, the inaudible sound will be played for 2 seconds as in my case it resolved an issue where the soundcard still needed to be initialized by a "real" sound, even if afterwards the silence sound was sufficient to keep it alive.
SoundPlayer does not allow playing simultaneous sounds and I found it not as reliable as NAudio.

I have also partially refactored the code according to C# style standards. I know that switching convention is always annoying, so feel free to revert these changes; if you have Resharper you should be able to automatically reformat it based on your standards. Ideally the repository should contain a Resharper code styling configuration so that it is straightforward to enforce the same standards.

### CODE REVIEW

**Comment by ngreyling** [comment]
@mayerwin Just curious: Shouldn't you have done a Sync with the upstream master branch before doing your commits? At the time of this PR, you're 25 commits behind where handruin:master is at.

**Comment by mayerwin** [comment]
Just saw that I wasn't working on the latest version, I am merging right now and will update.

**Comment by mayerwin** [comment]
For some reason I was convinced I was already synced... My bad.

**Comment by mayerwin** [comment]
There you go. I have merged the two branches. Hopefully there is no new bug (it works fine on my end).

**Comment by mayerwin** [comment]
Some more improvements...

**Comment by handruin** [comment]
Just FYI, I haven't forgotten, I've been really busy the past few days.  I plan to spend time tonight merging in this PR.  Thanks for contributing the changes.

**Comment by cibrhusk** [comment]
Hi handruin,
Thanks for your project, any chance you might pull maywin's request into the master branche any time soon for a new release? Particularly #20 is annoying and I very much prefer your solution to the alternatives out there.

**Comment by handruin** [comment]
Yes, I definitely need to revisit this.  I'll get this merged and a build asap.

**Comment by ngreyling** [comment]
When I try to Build Solution from this latest commit in master (https://github.com/handruin/spdif-ka/commit/c9a656064de54f6710d03380c40ebed4eceb5200), I get:

Error		Unable to load DLL 'mscorsn.dll': The specified module could not be found. (Exception from HRESULT: 0x8007007E)	SPDIFKA

**Pull request merged**
